package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9


import java.util.Date;

/**
 * ConceptAnswer generated by hbm2java
 */
public class ConceptAnswer  implements java.io.Serializable {


     private int conceptAnswerId;
     private int conceptId;
     private Integer answerConcept;
     private Integer answerDrug;
     private int creator;
     private Date dateCreated;
     private String uuid;

    public ConceptAnswer() {
    }

	
    public ConceptAnswer(int conceptAnswerId, int conceptId, int creator, Date dateCreated, String uuid) {
        this.conceptAnswerId = conceptAnswerId;
        this.conceptId = conceptId;
        this.creator = creator;
        this.dateCreated = dateCreated;
        this.uuid = uuid;
    }
    public ConceptAnswer(int conceptAnswerId, int conceptId, Integer answerConcept, Integer answerDrug, int creator, Date dateCreated, String uuid) {
       this.conceptAnswerId = conceptAnswerId;
       this.conceptId = conceptId;
       this.answerConcept = answerConcept;
       this.answerDrug = answerDrug;
       this.creator = creator;
       this.dateCreated = dateCreated;
       this.uuid = uuid;
    }
   
    public int getConceptAnswerId() {
        return this.conceptAnswerId;
    }
    
    public void setConceptAnswerId(int conceptAnswerId) {
        this.conceptAnswerId = conceptAnswerId;
    }
    public int getConceptId() {
        return this.conceptId;
    }
    
    public void setConceptId(int conceptId) {
        this.conceptId = conceptId;
    }
    public Integer getAnswerConcept() {
        return this.answerConcept;
    }
    
    public void setAnswerConcept(Integer answerConcept) {
        this.answerConcept = answerConcept;
    }
    public Integer getAnswerDrug() {
        return this.answerDrug;
    }
    
    public void setAnswerDrug(Integer answerDrug) {
        this.answerDrug = answerDrug;
    }
    public int getCreator() {
        return this.creator;
    }
    
    public void setCreator(int creator) {
        this.creator = creator;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


