package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9



/**
 * ConceptNumeric generated by hbm2java
 */
public class ConceptNumeric  implements java.io.Serializable {


     private int conceptId;
     private Double hiAbsolute;
     private Double hiCritical;
     private Double hiNormal;
     private Double lowAbsolute;
     private Double lowCritical;
     private Double lowNormal;
     private String units;
     private short precise;
     private String uuid;

    public ConceptNumeric() {
    }

	
    public ConceptNumeric(int conceptId, short precise, String uuid) {
        this.conceptId = conceptId;
        this.precise = precise;
        this.uuid = uuid;
    }
    public ConceptNumeric(int conceptId, Double hiAbsolute, Double hiCritical, Double hiNormal, Double lowAbsolute, Double lowCritical, Double lowNormal, String units, short precise, String uuid) {
       this.conceptId = conceptId;
       this.hiAbsolute = hiAbsolute;
       this.hiCritical = hiCritical;
       this.hiNormal = hiNormal;
       this.lowAbsolute = lowAbsolute;
       this.lowCritical = lowCritical;
       this.lowNormal = lowNormal;
       this.units = units;
       this.precise = precise;
       this.uuid = uuid;
    }
   
    public int getConceptId() {
        return this.conceptId;
    }
    
    public void setConceptId(int conceptId) {
        this.conceptId = conceptId;
    }
    public Double getHiAbsolute() {
        return this.hiAbsolute;
    }
    
    public void setHiAbsolute(Double hiAbsolute) {
        this.hiAbsolute = hiAbsolute;
    }
    public Double getHiCritical() {
        return this.hiCritical;
    }
    
    public void setHiCritical(Double hiCritical) {
        this.hiCritical = hiCritical;
    }
    public Double getHiNormal() {
        return this.hiNormal;
    }
    
    public void setHiNormal(Double hiNormal) {
        this.hiNormal = hiNormal;
    }
    public Double getLowAbsolute() {
        return this.lowAbsolute;
    }
    
    public void setLowAbsolute(Double lowAbsolute) {
        this.lowAbsolute = lowAbsolute;
    }
    public Double getLowCritical() {
        return this.lowCritical;
    }
    
    public void setLowCritical(Double lowCritical) {
        this.lowCritical = lowCritical;
    }
    public Double getLowNormal() {
        return this.lowNormal;
    }
    
    public void setLowNormal(Double lowNormal) {
        this.lowNormal = lowNormal;
    }
    public String getUnits() {
        return this.units;
    }
    
    public void setUnits(String units) {
        this.units = units;
    }
    public short getPrecise() {
        return this.precise;
    }
    
    public void setPrecise(short precise) {
        this.precise = precise;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


