package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9



/**
 * ConceptNameTagMapId generated by hbm2java
 */
public class ConceptNameTagMapId  implements java.io.Serializable {


     private int conceptNameId;
     private int conceptNameTagId;

    public ConceptNameTagMapId() {
    }

    public ConceptNameTagMapId(int conceptNameId, int conceptNameTagId) {
       this.conceptNameId = conceptNameId;
       this.conceptNameTagId = conceptNameTagId;
    }
   
    public int getConceptNameId() {
        return this.conceptNameId;
    }
    
    public void setConceptNameId(int conceptNameId) {
        this.conceptNameId = conceptNameId;
    }
    public int getConceptNameTagId() {
        return this.conceptNameTagId;
    }
    
    public void setConceptNameTagId(int conceptNameTagId) {
        this.conceptNameTagId = conceptNameTagId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConceptNameTagMapId) ) return false;
		 ConceptNameTagMapId castOther = ( ConceptNameTagMapId ) other; 
         
		 return (this.getConceptNameId()==castOther.getConceptNameId())
 && (this.getConceptNameTagId()==castOther.getConceptNameTagId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getConceptNameId();
         result = 37 * result + this.getConceptNameTagId();
         return result;
   }   


}


