package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9



/**
 * ConceptNameTagMap generated by hbm2java
 */
public class ConceptNameTagMap  implements java.io.Serializable {


     private ConceptNameTagMapId id;

    public ConceptNameTagMap() {
    }

    public ConceptNameTagMap(ConceptNameTagMapId id) {
       this.id = id;
    }
   
    public ConceptNameTagMapId getId() {
        return this.id;
    }
    
    public void setId(ConceptNameTagMapId id) {
        this.id = id;
    }




}


