package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9


import java.util.Collection;
import java.util.Date;
import java.util.HashSet;
import java.util.Locale;
import java.util.Vector;

import org.simpleframework.xml.ElementList;

/**
 * Concept generated by hbm2java
 */
public class Concept  implements java.io.Serializable {


     private Integer conceptId;
     private String version;
     private boolean retired;
     private String shortName;
     private String description;
     private String formText;
     private int datatypeId;
     private int classId;
     private boolean isSet;
     private User creator;
     private Date dateCreated;
     private Integer defaultCharge;
     private User changedBy;
     private Date dateChanged;
     private User retiredBy;
     private Date dateRetired;
     private String retireReason;
     private String uuid;
     
	private Collection<ConceptName> names;
	
	private Collection<ConceptAnswer> answers;
	
	private Collection<ConceptSet> conceptSets;
	
	private Collection<ConceptDescription> descriptions;
	

    public Concept() {
    }

	
    public Concept(int conceptId, boolean retired, int datatypeId, int classId, boolean isSet, User creator, Date dateCreated, String uuid) {
        this.conceptId = conceptId;
        this.retired = retired;
        this.datatypeId = datatypeId;
        this.classId = classId;
        this.isSet = isSet;
        this.creator = creator;
        this.dateCreated = dateCreated;
        this.uuid = uuid;
    }
    public Concept(int conceptId, boolean retired, String shortName, String description, String formText, int datatypeId, int classId, boolean isSet, User creator, Date dateCreated, Integer defaultCharge, User changedBy, Date dateChanged, User retiredBy, Date dateRetired, String retireReason, String uuid) {
       this.conceptId = conceptId;
       this.retired = retired;
       this.shortName = shortName;
       this.description = description;
       this.formText = formText;
       this.datatypeId = datatypeId;
       this.classId = classId;
       this.isSet = isSet;
       this.creator = creator;
       this.dateCreated = dateCreated;
       this.defaultCharge = defaultCharge;
       this.changedBy = changedBy;
       this.dateChanged = dateChanged;
       this.retiredBy = retiredBy;
       this.dateRetired = dateRetired;
       this.retireReason = retireReason;
       this.uuid = uuid;
    }
   
    public Integer getConceptId() {
        return this.conceptId;
    }
    
    public void setConceptId(Integer conceptId) {
        this.conceptId = conceptId;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    

	public String getShortName() {
        return this.shortName;
    }
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getFormText() {
        return this.formText;
    }
    
    public void setFormText(String formText) {
        this.formText = formText;
    }
    public int getDatatypeId() {
        return this.datatypeId;
    }
    
    public void setDatatypeId(int datatypeId) {
        this.datatypeId = datatypeId;
    }
    public int getClassId() {
        return this.classId;
    }
    
    public void setClassId(int classId) {
        this.classId = classId;
    }
    
    public void setSet(boolean isSet) {
		this.isSet = isSet;
	}


	public void setCreator(User creator) {
		this.creator = creator;
	}

    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getDefaultCharge() {
        return this.defaultCharge;
    }
    
    public void setDefaultCharge(Integer defaultCharge) {
        this.defaultCharge = defaultCharge;
    }
    
    public void setChangedBy(User changedBy) {
		this.changedBy = changedBy;
	}

    public Date getDateChanged() {
        return this.dateChanged;
    }
    
    public void setDateChanged(Date dateChanged) {
        this.dateChanged = dateChanged;
    }
    
    public void setRetiredBy(User retiredBy) {
		this.retiredBy = retiredBy;
	}


    public Date getDateRetired() {
        return this.dateRetired;
    }
    
    public void setDateRetired(Date dateRetired) {
        this.dateRetired = dateRetired;
    }
    public String getRetireReason() {
        return this.retireReason;
    }
    
    public void setRetireReason(String retireReason) {
        this.retireReason = retireReason;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    
    @ElementList
	public Collection<ConceptName> getNames() {
		return getNames(false);
	}
    public Collection<ConceptName> getNames(boolean includeVoided) {
		Collection<ConceptName> ret = new HashSet<ConceptName>();
		if (includeVoided) {
			if (names != null)
				return names;
			else
				return ret;
		} else {
			if (names != null) {
				for (ConceptName cn : names) {
					if (!cn.isVoided())
						ret.add(cn);
				}
			}
			return ret;
		}
	}


	public Collection<ConceptName> getNames(Locale locale) {
		Collection<ConceptName> localeNames = new Vector<ConceptName>();
		for (ConceptName possibleName : getNames()) {
			if (possibleName.getLocale().equals(locale)) {
				localeNames.add(possibleName);
			}
		}
		return localeNames;
	}


	public void addName(ConceptName clone) {
		// TODO Auto-generated method stub
		
	}
	




}


