package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9


import java.util.Date;

/**
 * ConceptSet generated by hbm2java
 */
public class ConceptSet  implements java.io.Serializable {


     private int conceptSetId;
     private int conceptId;
     private int conceptSet;
     private Double sortWeight;
     private int creator;
     private Date dateCreated;
     private String uuid;

    public ConceptSet() {
    }

	
    public ConceptSet(int conceptSetId, int conceptId, int conceptSet, int creator, Date dateCreated, String uuid) {
        this.conceptSetId = conceptSetId;
        this.conceptId = conceptId;
        this.conceptSet = conceptSet;
        this.creator = creator;
        this.dateCreated = dateCreated;
        this.uuid = uuid;
    }
    public ConceptSet(int conceptSetId, int conceptId, int conceptSet, Double sortWeight, int creator, Date dateCreated, String uuid) {
       this.conceptSetId = conceptSetId;
       this.conceptId = conceptId;
       this.conceptSet = conceptSet;
       this.sortWeight = sortWeight;
       this.creator = creator;
       this.dateCreated = dateCreated;
       this.uuid = uuid;
    }
   
    public int getConceptSetId() {
        return this.conceptSetId;
    }
    
    public void setConceptSetId(int conceptSetId) {
        this.conceptSetId = conceptSetId;
    }
    public int getConceptId() {
        return this.conceptId;
    }
    
    public void setConceptId(int conceptId) {
        this.conceptId = conceptId;
    }
    public int getConceptSet() {
        return this.conceptSet;
    }
    
    public void setConceptSet(int conceptSet) {
        this.conceptSet = conceptSet;
    }
    public Double getSortWeight() {
        return this.sortWeight;
    }
    
    public void setSortWeight(Double sortWeight) {
        this.sortWeight = sortWeight;
    }
    public int getCreator() {
        return this.creator;
    }
    
    public void setCreator(int creator) {
        this.creator = creator;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


