package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9


import java.util.Date;

/**
 * ConceptName generated by hbm2java
 */
public class ConceptName  implements java.io.Serializable {


     private int conceptNameId;
     private Integer conceptId;
     private String name;
     private String locale;
     private User creator;
     private Date dateCreated;
     private boolean voided;
     private Integer voidedBy;
     private Date dateVoided;
     private String voidReason;
     private String uuid;

    public ConceptName() {
    }

	
    public ConceptName(int conceptNameId, String name, String locale, User creator, Date dateCreated, boolean voided, String uuid) {
        this.conceptNameId = conceptNameId;
        this.name = name;
        this.locale = locale;
        this.creator = creator;
        this.dateCreated = dateCreated;
        this.voided = voided;
        this.uuid = uuid;
    }
    public ConceptName(int conceptNameId, Integer conceptId, String name, String locale, User creator, Date dateCreated, boolean voided, Integer voidedBy, Date dateVoided, String voidReason, String uuid) {
       this.conceptNameId = conceptNameId;
       this.conceptId = conceptId;
       this.name = name;
       this.locale = locale;
       this.creator = creator;
       this.dateCreated = dateCreated;
       this.voided = voided;
       this.voidedBy = voidedBy;
       this.dateVoided = dateVoided;
       this.voidReason = voidReason;
       this.uuid = uuid;
    }
   
    public int getConceptNameId() {
        return this.conceptNameId;
    }
    
    public void setConceptNameId(int conceptNameId) {
        this.conceptNameId = conceptNameId;
    }
    public Integer getConceptId() {
        return this.conceptId;
    }
    
    public void setConceptId(Integer conceptId) {
        this.conceptId = conceptId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLocale() {
        return this.locale;
    }
    
    public void setLocale(String locale) {
        this.locale = locale;
    }
    public User getCreator() {
        return this.creator;
    }
    
    public void setCreator(User creator) {
        this.creator = creator;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    public boolean isVoided() {
		return voided;
	}


	public void setVoided(boolean voided) {
		this.voided = voided;
	}


	public Integer getVoidedBy() {
        return this.voidedBy;
    }
    
    public void setVoidedBy(Integer voidedBy) {
        this.voidedBy = voidedBy;
    }
    public Date getDateVoided() {
        return this.dateVoided;
    }
    
    public void setDateVoided(Date dateVoided) {
        this.dateVoided = dateVoided;
    }
    public String getVoidReason() {
        return this.voidReason;
    }
    
    public void setVoidReason(String voidReason) {
        this.voidReason = voidReason;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


