package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9



/**
 * ConceptComplex generated by hbm2java
 */
public class ConceptComplex  implements java.io.Serializable {


     private int conceptId;
     private String handler;

    public ConceptComplex() {
    }

	
    public ConceptComplex(int conceptId) {
        this.conceptId = conceptId;
    }
    public ConceptComplex(int conceptId, String handler) {
       this.conceptId = conceptId;
       this.handler = handler;
    }
   
    public int getConceptId() {
        return this.conceptId;
    }
    
    public void setConceptId(int conceptId) {
        this.conceptId = conceptId;
    }
    public String getHandler() {
        return this.handler;
    }
    
    public void setHandler(String handler) {
        this.handler = handler;
    }




}


