package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9


import java.util.Date;

/**
 * Concept generated by hbm2java
 */
public class Concept  implements java.io.Serializable {


     private int conceptId;
     private String version;
     private short retired;
     private String shortName;
     private String description;
     private String formText;
     private int datatypeId;
     private int classId;
     private short isSet;
     private int creator;
     private Date dateCreated;
     private Integer defaultCharge;
     private Integer changedBy;
     private Date dateChanged;
     private Integer retiredBy;
     private Date dateRetired;
     private String retireReason;
     private String uuid;

    public Concept() {
    }

	
    public Concept(int conceptId, short retired, int datatypeId, int classId, short isSet, int creator, Date dateCreated, String uuid) {
        this.conceptId = conceptId;
        this.retired = retired;
        this.datatypeId = datatypeId;
        this.classId = classId;
        this.isSet = isSet;
        this.creator = creator;
        this.dateCreated = dateCreated;
        this.uuid = uuid;
    }
    public Concept(int conceptId, short retired, String shortName, String description, String formText, int datatypeId, int classId, short isSet, int creator, Date dateCreated, Integer defaultCharge, Integer changedBy, Date dateChanged, Integer retiredBy, Date dateRetired, String retireReason, String uuid) {
       this.conceptId = conceptId;
       this.retired = retired;
       this.shortName = shortName;
       this.description = description;
       this.formText = formText;
       this.datatypeId = datatypeId;
       this.classId = classId;
       this.isSet = isSet;
       this.creator = creator;
       this.dateCreated = dateCreated;
       this.defaultCharge = defaultCharge;
       this.changedBy = changedBy;
       this.dateChanged = dateChanged;
       this.retiredBy = retiredBy;
       this.dateRetired = dateRetired;
       this.retireReason = retireReason;
       this.uuid = uuid;
    }
   
    public int getConceptId() {
        return this.conceptId;
    }
    
    public void setConceptId(int conceptId) {
        this.conceptId = conceptId;
    }
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }
    public short getRetired() {
        return this.retired;
    }
    
    public void setRetired(short retired) {
        this.retired = retired;
    }
    public String getShortName() {
        return this.shortName;
    }
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getFormText() {
        return this.formText;
    }
    
    public void setFormText(String formText) {
        this.formText = formText;
    }
    public int getDatatypeId() {
        return this.datatypeId;
    }
    
    public void setDatatypeId(int datatypeId) {
        this.datatypeId = datatypeId;
    }
    public int getClassId() {
        return this.classId;
    }
    
    public void setClassId(int classId) {
        this.classId = classId;
    }
    public short getIsSet() {
        return this.isSet;
    }
    
    public void setIsSet(short isSet) {
        this.isSet = isSet;
    }
    public int getCreator() {
        return this.creator;
    }
    
    public void setCreator(int creator) {
        this.creator = creator;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getDefaultCharge() {
        return this.defaultCharge;
    }
    
    public void setDefaultCharge(Integer defaultCharge) {
        this.defaultCharge = defaultCharge;
    }
    public Integer getChangedBy() {
        return this.changedBy;
    }
    
    public void setChangedBy(Integer changedBy) {
        this.changedBy = changedBy;
    }
    public Date getDateChanged() {
        return this.dateChanged;
    }
    
    public void setDateChanged(Date dateChanged) {
        this.dateChanged = dateChanged;
    }
    public Integer getRetiredBy() {
        return this.retiredBy;
    }
    
    public void setRetiredBy(Integer retiredBy) {
        this.retiredBy = retiredBy;
    }
    public Date getDateRetired() {
        return this.dateRetired;
    }
    
    public void setDateRetired(Date dateRetired) {
        this.dateRetired = dateRetired;
    }
    public String getRetireReason() {
        return this.retireReason;
    }
    
    public void setRetireReason(String retireReason) {
        this.retireReason = retireReason;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


