package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9


import java.util.Date;

/**
 * ConceptDescription generated by hbm2java
 */
public class ConceptDescription  implements java.io.Serializable {


     private int conceptDescriptionId;
     private int conceptId;
     private String description;
     private String locale;
     private int creator;
     private Date dateCreated;
     private Integer changedBy;
     private Date dateChanged;
     private String uuid;

    public ConceptDescription() {
    }

	
    public ConceptDescription(int conceptDescriptionId, int conceptId, String description, String locale, int creator, Date dateCreated, String uuid) {
        this.conceptDescriptionId = conceptDescriptionId;
        this.conceptId = conceptId;
        this.description = description;
        this.locale = locale;
        this.creator = creator;
        this.dateCreated = dateCreated;
        this.uuid = uuid;
    }
    public ConceptDescription(int conceptDescriptionId, int conceptId, String description, String locale, int creator, Date dateCreated, Integer changedBy, Date dateChanged, String uuid) {
       this.conceptDescriptionId = conceptDescriptionId;
       this.conceptId = conceptId;
       this.description = description;
       this.locale = locale;
       this.creator = creator;
       this.dateCreated = dateCreated;
       this.changedBy = changedBy;
       this.dateChanged = dateChanged;
       this.uuid = uuid;
    }
   
    public int getConceptDescriptionId() {
        return this.conceptDescriptionId;
    }
    
    public void setConceptDescriptionId(int conceptDescriptionId) {
        this.conceptDescriptionId = conceptDescriptionId;
    }
    public int getConceptId() {
        return this.conceptId;
    }
    
    public void setConceptId(int conceptId) {
        this.conceptId = conceptId;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getLocale() {
        return this.locale;
    }
    
    public void setLocale(String locale) {
        this.locale = locale;
    }
    public int getCreator() {
        return this.creator;
    }
    
    public void setCreator(int creator) {
        this.creator = creator;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getChangedBy() {
        return this.changedBy;
    }
    
    public void setChangedBy(Integer changedBy) {
        this.changedBy = changedBy;
    }
    public Date getDateChanged() {
        return this.dateChanged;
    }
    
    public void setDateChanged(Date dateChanged) {
        this.dateChanged = dateChanged;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


