package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9


import java.util.Date;

/**
 * Databasechangelog generated by hbm2java
 */
public class Databasechangelog  implements java.io.Serializable {


     private DatabasechangelogId id;
     private Date dateexecuted;
     private String md5sum;
     private String description;
     private String comments;
     private String tag;
     private String liquibase;

    public Databasechangelog() {
    }

	
    public Databasechangelog(DatabasechangelogId id, Date dateexecuted) {
        this.id = id;
        this.dateexecuted = dateexecuted;
    }
    public Databasechangelog(DatabasechangelogId id, Date dateexecuted, String md5sum, String description, String comments, String tag, String liquibase) {
       this.id = id;
       this.dateexecuted = dateexecuted;
       this.md5sum = md5sum;
       this.description = description;
       this.comments = comments;
       this.tag = tag;
       this.liquibase = liquibase;
    }
   
    public DatabasechangelogId getId() {
        return this.id;
    }
    
    public void setId(DatabasechangelogId id) {
        this.id = id;
    }
    public Date getDateexecuted() {
        return this.dateexecuted;
    }
    
    public void setDateexecuted(Date dateexecuted) {
        this.dateexecuted = dateexecuted;
    }
    public String getMd5sum() {
        return this.md5sum;
    }
    
    public void setMd5sum(String md5sum) {
        this.md5sum = md5sum;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }
    public String getLiquibase() {
        return this.liquibase;
    }
    
    public void setLiquibase(String liquibase) {
        this.liquibase = liquibase;
    }




}


