package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9



/**
 * GlobalProperty generated by hbm2java
 */
public class GlobalProperty  implements java.io.Serializable {


     private String property;
     private String propertyValue;
     private String description;

    public GlobalProperty() {
    }

	
    public GlobalProperty(String property) {
        this.property = property;
    }
    public GlobalProperty(String property, String propertyValue, String description) {
       this.property = property;
       this.propertyValue = propertyValue;
       this.description = description;
    }
   
    public String getProperty() {
        return this.property;
    }
    
    public void setProperty(String property) {
        this.property = property;
    }
    public String getPropertyValue() {
        return this.propertyValue;
    }
    
    public void setPropertyValue(String propertyValue) {
        this.propertyValue = propertyValue;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


