package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9


import java.util.Date;

/**
 * GroupType generated by hbm2java
 */
public class GroupType  implements java.io.Serializable {


     private int groupTypeId;
     private String name;
     private String description;
     private Integer creator;
     private Date dateCreated;
     private Integer changedBy;
     private Date dateChanged;
     private String uuid;

    public GroupType() {
    }

	
    public GroupType(int groupTypeId, String uuid) {
        this.groupTypeId = groupTypeId;
        this.uuid = uuid;
    }
    public GroupType(int groupTypeId, String name, String description, Integer creator, Date dateCreated, Integer changedBy, Date dateChanged, String uuid) {
       this.groupTypeId = groupTypeId;
       this.name = name;
       this.description = description;
       this.creator = creator;
       this.dateCreated = dateCreated;
       this.changedBy = changedBy;
       this.dateChanged = dateChanged;
       this.uuid = uuid;
    }
   
    public int getGroupTypeId() {
        return this.groupTypeId;
    }
    
    public void setGroupTypeId(int groupTypeId) {
        this.groupTypeId = groupTypeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getCreator() {
        return this.creator;
    }
    
    public void setCreator(Integer creator) {
        this.creator = creator;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getChangedBy() {
        return this.changedBy;
    }
    
    public void setChangedBy(Integer changedBy) {
        this.changedBy = changedBy;
    }
    public Date getDateChanged() {
        return this.dateChanged;
    }
    
    public void setDateChanged(Date dateChanged) {
        this.dateChanged = dateChanged;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


