package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9



/**
 * GroupMapType generated by hbm2java
 */
public class GroupMapType  implements java.io.Serializable {


     private int groupMapTypeId;
     private String name;
     private String description;

    public GroupMapType() {
    }

    public GroupMapType(int groupMapTypeId, String name, String description) {
       this.groupMapTypeId = groupMapTypeId;
       this.name = name;
       this.description = description;
    }
   
    public int getGroupMapTypeId() {
        return this.groupMapTypeId;
    }
    
    public void setGroupMapTypeId(int groupMapTypeId) {
        this.groupMapTypeId = groupMapTypeId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


