package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9



/**
 * GroupMap generated by hbm2java
 */
public class GroupMap  implements java.io.Serializable {


     private int groupMapId;
     private Integer groupMapType;
     private int group1;
     private int group2;

    public GroupMap() {
    }

	
    public GroupMap(int groupMapId, int group1, int group2) {
        this.groupMapId = groupMapId;
        this.group1 = group1;
        this.group2 = group2;
    }
    public GroupMap(int groupMapId, Integer groupMapType, int group1, int group2) {
       this.groupMapId = groupMapId;
       this.groupMapType = groupMapType;
       this.group1 = group1;
       this.group2 = group2;
    }
   
    public int getGroupMapId() {
        return this.groupMapId;
    }
    
    public void setGroupMapId(int groupMapId) {
        this.groupMapId = groupMapId;
    }
    public Integer getGroupMapType() {
        return this.groupMapType;
    }
    
    public void setGroupMapType(Integer groupMapType) {
        this.groupMapType = groupMapType;
    }
    public int getGroup1() {
        return this.group1;
    }
    
    public void setGroup1(int group1) {
        this.group1 = group1;
    }
    public int getGroup2() {
        return this.group2;
    }
    
    public void setGroup2(int group2) {
        this.group2 = group2;
    }




}


