package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9


import java.util.Date;

/**
 * GroupMembership generated by hbm2java
 */
public class GroupMembership  implements java.io.Serializable {


     private int groupMembershipId;
     private Integer groupId;
     private Integer personId;
     private int groupMembershipType;
     private Date startDate;
     private Date endDate;
     private Integer creator;
     private Date dateCreated;
     private Integer voided;
     private Integer voidedBy;
     private Date dateVoided;
     private String voidReason;
     private String uuid;

    public GroupMembership() {
    }

	
    public GroupMembership(int groupMembershipId, int groupMembershipType, String uuid) {
        this.groupMembershipId = groupMembershipId;
        this.groupMembershipType = groupMembershipType;
        this.uuid = uuid;
    }
    public GroupMembership(int groupMembershipId, Integer groupId, Integer personId, int groupMembershipType, Date startDate, Date endDate, Integer creator, Date dateCreated, Integer voided, Integer voidedBy, Date dateVoided, String voidReason, String uuid) {
       this.groupMembershipId = groupMembershipId;
       this.groupId = groupId;
       this.personId = personId;
       this.groupMembershipType = groupMembershipType;
       this.startDate = startDate;
       this.endDate = endDate;
       this.creator = creator;
       this.dateCreated = dateCreated;
       this.voided = voided;
       this.voidedBy = voidedBy;
       this.dateVoided = dateVoided;
       this.voidReason = voidReason;
       this.uuid = uuid;
    }
   
    public int getGroupMembershipId() {
        return this.groupMembershipId;
    }
    
    public void setGroupMembershipId(int groupMembershipId) {
        this.groupMembershipId = groupMembershipId;
    }
    public Integer getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
    public Integer getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }
    public int getGroupMembershipType() {
        return this.groupMembershipType;
    }
    
    public void setGroupMembershipType(int groupMembershipType) {
        this.groupMembershipType = groupMembershipType;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Integer getCreator() {
        return this.creator;
    }
    
    public void setCreator(Integer creator) {
        this.creator = creator;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getVoided() {
        return this.voided;
    }
    
    public void setVoided(Integer voided) {
        this.voided = voided;
    }
    public Integer getVoidedBy() {
        return this.voidedBy;
    }
    
    public void setVoidedBy(Integer voidedBy) {
        this.voidedBy = voidedBy;
    }
    public Date getDateVoided() {
        return this.dateVoided;
    }
    
    public void setDateVoided(Date dateVoided) {
        this.dateVoided = dateVoided;
    }
    public String getVoidReason() {
        return this.voidReason;
    }
    
    public void setVoidReason(String voidReason) {
        this.voidReason = voidReason;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


