package org.openhouse.api.database.model;

// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * GroupMembershipType generated by hbm2java
 */
public class GroupMembershipType implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int groupMembershipTypeId;
	private String name;
	private String description;
	private int creator;
	private Date dateCreated;
	private String uuid;

	public GroupMembershipType() {
	}

	public GroupMembershipType(int groupMembershipTypeId, String name,
			String description, int creator, Date dateCreated, String uuid) {
		this.groupMembershipTypeId = groupMembershipTypeId;
		this.name = name;
		this.description = description;
		this.creator = creator;
		this.dateCreated = dateCreated;
		this.uuid = uuid;
	}

	public int getGroupMembershipTypeId() {
		return this.groupMembershipTypeId;
	}

	public void setGroupMembershipTypeId(int groupMembershipTypeId) {
		this.groupMembershipTypeId = groupMembershipTypeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getCreator() {
		return this.creator;
	}

	public void setCreator(int creator) {
		this.creator = creator;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

}
