package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9


import java.util.Date;

/**
 * Note generated by hbm2java
 */
public class Note  implements java.io.Serializable {


     private int noteId;
     private String noteType;
     private Integer patientId;
     private Integer obsId;
     private Integer encounterId;
     private String text;
     private Integer priority;
     private Integer parent;
     private int creator;
     private Date dateCreated;
     private Integer changedBy;
     private Date dateChanged;
     private String uuid;

    public Note() {
    }

	
    public Note(int noteId, String text, int creator, Date dateCreated, String uuid) {
        this.noteId = noteId;
        this.text = text;
        this.creator = creator;
        this.dateCreated = dateCreated;
        this.uuid = uuid;
    }
    public Note(int noteId, String noteType, Integer patientId, Integer obsId, Integer encounterId, String text, Integer priority, Integer parent, int creator, Date dateCreated, Integer changedBy, Date dateChanged, String uuid) {
       this.noteId = noteId;
       this.noteType = noteType;
       this.patientId = patientId;
       this.obsId = obsId;
       this.encounterId = encounterId;
       this.text = text;
       this.priority = priority;
       this.parent = parent;
       this.creator = creator;
       this.dateCreated = dateCreated;
       this.changedBy = changedBy;
       this.dateChanged = dateChanged;
       this.uuid = uuid;
    }
   
    public int getNoteId() {
        return this.noteId;
    }
    
    public void setNoteId(int noteId) {
        this.noteId = noteId;
    }
    public String getNoteType() {
        return this.noteType;
    }
    
    public void setNoteType(String noteType) {
        this.noteType = noteType;
    }
    public Integer getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(Integer patientId) {
        this.patientId = patientId;
    }
    public Integer getObsId() {
        return this.obsId;
    }
    
    public void setObsId(Integer obsId) {
        this.obsId = obsId;
    }
    public Integer getEncounterId() {
        return this.encounterId;
    }
    
    public void setEncounterId(Integer encounterId) {
        this.encounterId = encounterId;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Integer getPriority() {
        return this.priority;
    }
    
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
    public Integer getParent() {
        return this.parent;
    }
    
    public void setParent(Integer parent) {
        this.parent = parent;
    }
    public int getCreator() {
        return this.creator;
    }
    
    public void setCreator(int creator) {
        this.creator = creator;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getChangedBy() {
        return this.changedBy;
    }
    
    public void setChangedBy(Integer changedBy) {
        this.changedBy = changedBy;
    }
    public Date getDateChanged() {
        return this.dateChanged;
    }
    
    public void setDateChanged(Date dateChanged) {
        this.dateChanged = dateChanged;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


