package org.openhouse.api.database.model;

// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * Obs generated by hbm2java
 */
public class Obs implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int obsId;
	private int groupId;
	private Integer encounterId;
	private int conceptId;
	private Date obsDatetime;
	private Integer obsGroupId;
	private String accessionNumber;
	private Integer valueGroupId;
	private Integer valueCoded;
	private Integer valueCodedNameId;
	private String valueComplex;
	private Date valueDatetime;
	private Double valueNumeric;
	private String valueModifier;
	private String valueText;
	private Date dateStarted;
	private Date dateStopped;
	private String comments;
	private int creator;
	private Date dateCreated;
	private short voided;
	private Integer voidedBy;
	private Date dateVoided;
	private String voidReason;
	private String uuid;

	public Obs() {
	}

	public Obs(int obsId, int groupId, int conceptId, Date obsDatetime,
			int creator, Date dateCreated, short voided, String uuid) {
		this.obsId = obsId;
		this.groupId = groupId;
		this.conceptId = conceptId;
		this.obsDatetime = obsDatetime;
		this.creator = creator;
		this.dateCreated = dateCreated;
		this.voided = voided;
		this.uuid = uuid;
	}

	public Obs(int obsId, int groupId, Integer encounterId, int conceptId,
			Date obsDatetime, Integer obsGroupId, String accessionNumber,
			Integer valueGroupId, Integer valueCoded, Integer valueCodedNameId,
			String valueComplex, Date valueDatetime, Double valueNumeric,
			String valueModifier, String valueText, Date dateStarted,
			Date dateStopped, String comments, int creator, Date dateCreated,
			short voided, Integer voidedBy, Date dateVoided, String voidReason,
			String uuid) {
		this.obsId = obsId;
		this.groupId = groupId;
		this.encounterId = encounterId;
		this.conceptId = conceptId;
		this.obsDatetime = obsDatetime;
		this.obsGroupId = obsGroupId;
		this.accessionNumber = accessionNumber;
		this.valueGroupId = valueGroupId;
		this.valueCoded = valueCoded;
		this.valueCodedNameId = valueCodedNameId;
		this.valueComplex = valueComplex;
		this.valueDatetime = valueDatetime;
		this.valueNumeric = valueNumeric;
		this.valueModifier = valueModifier;
		this.valueText = valueText;
		this.dateStarted = dateStarted;
		this.dateStopped = dateStopped;
		this.comments = comments;
		this.creator = creator;
		this.dateCreated = dateCreated;
		this.voided = voided;
		this.voidedBy = voidedBy;
		this.dateVoided = dateVoided;
		this.voidReason = voidReason;
		this.uuid = uuid;
	}

	public int getObsId() {
		return this.obsId;
	}

	public void setObsId(int obsId) {
		this.obsId = obsId;
	}

	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	public Integer getEncounterId() {
		return this.encounterId;
	}

	public void setEncounterId(Integer encounterId) {
		this.encounterId = encounterId;
	}

	public int getConceptId() {
		return this.conceptId;
	}

	public void setConceptId(int conceptId) {
		this.conceptId = conceptId;
	}

	public Date getObsDatetime() {
		return this.obsDatetime;
	}

	public void setObsDatetime(Date obsDatetime) {
		this.obsDatetime = obsDatetime;
	}

	public Integer getObsGroupId() {
		return this.obsGroupId;
	}

	public void setObsGroupId(Integer obsGroupId) {
		this.obsGroupId = obsGroupId;
	}

	public String getAccessionNumber() {
		return this.accessionNumber;
	}

	public void setAccessionNumber(String accessionNumber) {
		this.accessionNumber = accessionNumber;
	}

	public Integer getValueGroupId() {
		return this.valueGroupId;
	}

	public void setValueGroupId(Integer valueGroupId) {
		this.valueGroupId = valueGroupId;
	}

	public Integer getValueCoded() {
		return this.valueCoded;
	}

	public void setValueCoded(Integer valueCoded) {
		this.valueCoded = valueCoded;
	}

	public Integer getValueCodedNameId() {
		return this.valueCodedNameId;
	}

	public void setValueCodedNameId(Integer valueCodedNameId) {
		this.valueCodedNameId = valueCodedNameId;
	}

	public String getValueComplex() {
		return this.valueComplex;
	}

	public void setValueComplex(String valueComplex) {
		this.valueComplex = valueComplex;
	}

	public Date getValueDatetime() {
		return this.valueDatetime;
	}

	public void setValueDatetime(Date valueDatetime) {
		this.valueDatetime = valueDatetime;
	}

	public Double getValueNumeric() {
		return this.valueNumeric;
	}

	public void setValueNumeric(Double valueNumeric) {
		this.valueNumeric = valueNumeric;
	}

	public String getValueModifier() {
		return this.valueModifier;
	}

	public void setValueModifier(String valueModifier) {
		this.valueModifier = valueModifier;
	}

	public String getValueText() {
		return this.valueText;
	}

	public void setValueText(String valueText) {
		this.valueText = valueText;
	}

	public Date getDateStarted() {
		return this.dateStarted;
	}

	public void setDateStarted(Date dateStarted) {
		this.dateStarted = dateStarted;
	}

	public Date getDateStopped() {
		return this.dateStopped;
	}

	public void setDateStopped(Date dateStopped) {
		this.dateStopped = dateStopped;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public int getCreator() {
		return this.creator;
	}

	public void setCreator(int creator) {
		this.creator = creator;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public short getVoided() {
		return this.voided;
	}

	public void setVoided(short voided) {
		this.voided = voided;
	}

	public Integer getVoidedBy() {
		return this.voidedBy;
	}

	public void setVoidedBy(Integer voidedBy) {
		this.voidedBy = voidedBy;
	}

	public Date getDateVoided() {
		return this.dateVoided;
	}

	public void setDateVoided(Date dateVoided) {
		this.dateVoided = dateVoided;
	}

	public String getVoidReason() {
		return this.voidReason;
	}

	public void setVoidReason(String voidReason) {
		this.voidReason = voidReason;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

}
