package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9



/**
 * RolePrivilegeId generated by hbm2java
 */
public class RolePrivilegeId  implements java.io.Serializable {


     private String privilege;
     private String role;

    public RolePrivilegeId() {
    }

    public RolePrivilegeId(String privilege, String role) {
       this.privilege = privilege;
       this.role = role;
    }
   
    public String getPrivilege() {
        return this.privilege;
    }
    
    public void setPrivilege(String privilege) {
        this.privilege = privilege;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RolePrivilegeId) ) return false;
		 RolePrivilegeId castOther = ( RolePrivilegeId ) other; 
         
		 return ( (this.getPrivilege()==castOther.getPrivilege()) || ( this.getPrivilege()!=null && castOther.getPrivilege()!=null && this.getPrivilege().equals(castOther.getPrivilege()) ) )
 && ( (this.getRole()==castOther.getRole()) || ( this.getRole()!=null && castOther.getRole()!=null && this.getRole().equals(castOther.getRole()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPrivilege() == null ? 0 : this.getPrivilege().hashCode() );
         result = 37 * result + ( getRole() == null ? 0 : this.getRole().hashCode() );
         return result;
   }   


}


