package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9



/**
 * RolePrivilege generated by hbm2java
 */
public class RolePrivilege  implements java.io.Serializable {


     private RolePrivilegeId id;

    public RolePrivilege() {
    }

    public RolePrivilege(RolePrivilegeId id) {
       this.id = id;
    }
   
    public RolePrivilegeId getId() {
        return this.id;
    }
    
    public void setId(RolePrivilegeId id) {
        this.id = id;
    }




}


