package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9



/**
 * RoleRole generated by hbm2java
 */
public class RoleRole  implements java.io.Serializable {


     private RoleRoleId id;

    public RoleRole() {
    }

    public RoleRole(RoleRoleId id) {
       this.id = id;
    }
   
    public RoleRoleId getId() {
        return this.id;
    }
    
    public void setId(RoleRoleId id) {
        this.id = id;
    }




}


