package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9


import java.util.Date;

/**
 * SchedulerTaskConfig generated by hbm2java
 */
public class SchedulerTaskConfig  implements java.io.Serializable {


     private int taskConfigId;
     private String name;
     private String description;
     private String schedulableClass;
     private Date startTime;
     private String startTimePattern;
     private int repeatInterval;
     private int startOnStartup;
     private int started;
     private Integer createdBy;
     private Date dateCreated;
     private Integer changedBy;
     private Date dateChanged;

    public SchedulerTaskConfig() {
    }

	
    public SchedulerTaskConfig(int taskConfigId, String name, int repeatInterval, int startOnStartup, int started) {
        this.taskConfigId = taskConfigId;
        this.name = name;
        this.repeatInterval = repeatInterval;
        this.startOnStartup = startOnStartup;
        this.started = started;
    }
    public SchedulerTaskConfig(int taskConfigId, String name, String description, String schedulableClass, Date startTime, String startTimePattern, int repeatInterval, int startOnStartup, int started, Integer createdBy, Date dateCreated, Integer changedBy, Date dateChanged) {
       this.taskConfigId = taskConfigId;
       this.name = name;
       this.description = description;
       this.schedulableClass = schedulableClass;
       this.startTime = startTime;
       this.startTimePattern = startTimePattern;
       this.repeatInterval = repeatInterval;
       this.startOnStartup = startOnStartup;
       this.started = started;
       this.createdBy = createdBy;
       this.dateCreated = dateCreated;
       this.changedBy = changedBy;
       this.dateChanged = dateChanged;
    }
   
    public int getTaskConfigId() {
        return this.taskConfigId;
    }
    
    public void setTaskConfigId(int taskConfigId) {
        this.taskConfigId = taskConfigId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getSchedulableClass() {
        return this.schedulableClass;
    }
    
    public void setSchedulableClass(String schedulableClass) {
        this.schedulableClass = schedulableClass;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public String getStartTimePattern() {
        return this.startTimePattern;
    }
    
    public void setStartTimePattern(String startTimePattern) {
        this.startTimePattern = startTimePattern;
    }
    public int getRepeatInterval() {
        return this.repeatInterval;
    }
    
    public void setRepeatInterval(int repeatInterval) {
        this.repeatInterval = repeatInterval;
    }
    public int getStartOnStartup() {
        return this.startOnStartup;
    }
    
    public void setStartOnStartup(int startOnStartup) {
        this.startOnStartup = startOnStartup;
    }
    public int getStarted() {
        return this.started;
    }
    
    public void setStarted(int started) {
        this.started = started;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getChangedBy() {
        return this.changedBy;
    }
    
    public void setChangedBy(Integer changedBy) {
        this.changedBy = changedBy;
    }
    public Date getDateChanged() {
        return this.dateChanged;
    }
    
    public void setDateChanged(Date dateChanged) {
        this.dateChanged = dateChanged;
    }




}


