package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9



/**
 * SchedulerTaskConfigProperty generated by hbm2java
 */
public class SchedulerTaskConfigProperty  implements java.io.Serializable {


     private int taskConfigPropertyId;
     private String name;
     private String value;
     private Integer taskConfigId;

    public SchedulerTaskConfigProperty() {
    }

	
    public SchedulerTaskConfigProperty(int taskConfigPropertyId, String name) {
        this.taskConfigPropertyId = taskConfigPropertyId;
        this.name = name;
    }
    public SchedulerTaskConfigProperty(int taskConfigPropertyId, String name, String value, Integer taskConfigId) {
       this.taskConfigPropertyId = taskConfigPropertyId;
       this.name = name;
       this.value = value;
       this.taskConfigId = taskConfigId;
    }
   
    public int getTaskConfigPropertyId() {
        return this.taskConfigPropertyId;
    }
    
    public void setTaskConfigPropertyId(int taskConfigPropertyId) {
        this.taskConfigPropertyId = taskConfigPropertyId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Integer getTaskConfigId() {
        return this.taskConfigId;
    }
    
    public void setTaskConfigId(Integer taskConfigId) {
        this.taskConfigId = taskConfigId;
    }




}


