package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9



/**
 * UserRole generated by hbm2java
 */
public class UserRole  implements java.io.Serializable {


     private UserRoleId id;

    public UserRole() {
    }

    public UserRole(UserRoleId id) {
       this.id = id;
    }
   
    public UserRoleId getId() {
        return this.id;
    }
    
    public void setId(UserRoleId id) {
        this.id = id;
    }




}


