package org.openhouse.api.database.model;
// Generated May 6, 2010 12:58:59 PM by Hibernate Tools 3.2.0.b9



/**
 * UserProperty generated by hbm2java
 */
public class UserProperty  implements java.io.Serializable {


     private UserPropertyId id;
     private String propertyValue;
     private String uuid;

    public UserProperty() {
    }

    public UserProperty(UserPropertyId id, String propertyValue, String uuid) {
       this.id = id;
       this.propertyValue = propertyValue;
       this.uuid = uuid;
    }
   
    public UserPropertyId getId() {
        return this.id;
    }
    
    public void setId(UserPropertyId id) {
        this.id = id;
    }
    public String getPropertyValue() {
        return this.propertyValue;
    }
    
    public void setPropertyValue(String propertyValue) {
        this.propertyValue = propertyValue;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }




}


